project:
  type: book
  output-dir: docs

book:
  title: "Química Cuántica I"
  author: "JEBV"
  date: "8/10/2023"
  chapters:
    - index.qmd
    - part: "1. Fundamentos de la mecánica cuántica"
      chapters: 
        - 1_1_postulados.qmd
        - 1_2_probabilidad.qmd
    - part: "2. Aplicaciones de la mecánica cuántica a sistemas sencillos"
      chapters:
        - 2_1_particulalibre.qmd
    - part: "3. Átomo de hidrógeno"
    - part: "4. Métodos aproximados"
    - part: "5. Dos electrones: Helio"
    - part: "6. Sistemas de muchos electrones"
    - part: "7. Hartree-Fock"
    - part: "8. Más allá de HF: la correlación electrónica"
    - part: "9. Teoría de funcionales de la densidad"
    - part: "10. Espectroscopía molecular"
    - part: "Apéndice: Mathematica"
      chapters: 
        - A_1_derivadas.qmd
    - part: "Apéndice: python"
      chapters: 
        - B_1_pycalculadora.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    light: flatly
    dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt