project:
  type: book
  output-dir: docs

book:
  title: "Química Cuántica I"
  author: "JEBV"
  date: "8/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    light: flatly
    dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt